using System.Text.Json.Nodes;
using Issun.Core;
using Issun.Core.Server;

namespace Issun.Core.Tests.Server;

/// <summary>
/// GET /now-playing's body against what relay.py's public_state() produced for
/// the same state. Every Expected string below was generated by importing
/// relay.py 1.9.0, setting its State, _artwork_cache and _links_cache to match,
/// freezing time.time() at <see cref="Now"/>, and running json.dumps(public_state()).
/// They are committed as literals so the tests need no Python.
///
/// updated_at is set as Now - Age in both languages, so the age the projection
/// computes (Now - updated_at) carries the same floating-point error in each —
/// which is why "partial_links" rounds 89.95 to 90.0 and still reads as fresh.
/// </summary>
public class ProjectionTests
{
    public const double Now = 1_758_400_000.0;

    public sealed record Case(
        string Name,
        string? Body,
        double? Age,
        Dictionary<string, string> Artwork,
        Dictionary<string, CatalogLinks> Links,
        string Expected);

    public static readonly Case[] Cases =
    [
        new("never",
            Body: null,
            Age: null,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": false, "stale": true, "updated_ago": null}"""),
        new("farewell",
            Body: """{"playing": false, "seq": 5}""",
            Age: 3.25,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": false, "stale": false, "updated_ago": 3.2}"""),
        new("full",
            Body: """{"playing": true, "title": "i", "artist": "Kendrick Lamar", "album": "i - Single", "duration": 231.45, "elapsed": 12.35, "store_id": "1440894925", "diag": {"engine_running": true}, "artwork_b64": "/9j/AAAA"}""",
            Age: 0.05,
            Artwork: new() { ["1440894925"] = "https://is1-ssl.mzstatic.com/image/thumb/x/512x512bb.jpg" },
            Links: new() { ["1440894925"] = new CatalogLinks("https://music.apple.com/us/album/i/1?i=2", "https://music.apple.com/us/artist/k/3", "https://music.apple.com/us/album/i/1") },
            Expected: """{"playing": true, "stale": false, "updated_ago": 0.0, "title": "i", "artist": "Kendrick Lamar", "album": "i - Single", "duration": 231.4, "elapsed": 12.3, "artwork": "https://is1-ssl.mzstatic.com/image/thumb/x/512x512bb.jpg", "links": {"song": "https://music.apple.com/us/album/i/1?i=2", "artist": "https://music.apple.com/us/artist/k/3", "album": "https://music.apple.com/us/album/i/1"}}"""),
        new("stale",
            Body: """{"playing": true, "title": "Old", "artist": "A"}""",
            Age: 95.0,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": false, "stale": true, "updated_ago": 95.0}"""),
        new("exactly_idle",
            Body: """{"playing": true, "title": "Old", "artist": "A"}""",
            Age: 90.0,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": false, "stale": true, "updated_ago": 90.0}"""),
        new("escapes",
            Body: """{"playing": true, "title": "Caf\u00e9 \"quoted\" \\ back/slash\n\t\u2060", "artist": "\ud83c\udfb5 Bj\u00f6rk <&>'", "album": "", "duration": 200, "store_id": "0"}""",
            Age: 1.0,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": true, "stale": false, "updated_ago": 1.0, "title": "Caf\u00e9 \"quoted\" \\ back/slash\n\t\u2060", "artist": "\ud83c\udfb5 Bj\u00f6rk <&>'", "duration": 200.0}"""),
        new("partial_links",
            Body: """{"playing": true, "title": "T", "artist": "A", "album": "B", "duration": 180.0, "elapsed": -0.04, "store_id": "42"}""",
            Age: 89.95,
            Artwork: new() { ["42"] = "" },
            Links: new() { ["42"] = new CatalogLinks("https://music.apple.com/us/song/t/42", null, null) },
            Expected: """{"playing": true, "stale": false, "updated_ago": 90.0, "title": "T", "artist": "A", "album": "B", "duration": 180.0, "elapsed": -0.0, "links": {"song": "https://music.apple.com/us/song/t/42"}}"""),
        new("empty_links",
            Body: """{"playing": true, "title": "T", "artist": "A", "duration": 1e+16, "elapsed": 1e-05, "store_id": "43"}""",
            Age: 0.0,
            Artwork: new() { ["43"] = "https://example.invalid/43.jpg" },
            Links: new() { ["43"] = new CatalogLinks(null, null, null) },
            Expected: """{"playing": true, "stale": false, "updated_ago": 0.0, "title": "T", "artist": "A", "duration": 1e+16, "elapsed": 0.0, "artwork": "https://example.invalid/43.jpg"}"""),
        new("no_store_id_cached_elsewhere",
            Body: """{"playing": true, "title": "T", "elapsed": 2.5, "duration": 0.25}""",
            Age: 12.75,
            Artwork: new() { ["44"] = "https://example.invalid/44.jpg" },
            Links: new() {  },
            Expected: """{"playing": true, "stale": false, "updated_ago": 12.8, "title": "T", "duration": 0.2, "elapsed": 2.5}"""),
        new("big_small",
            Body: """{"playing": true, "title": "T", "duration": 1234567890123456.8, "elapsed": 0.15}""",
            Age: 0.35,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": true, "stale": false, "updated_ago": 0.3, "title": "T", "duration": 1234567890123456.8, "elapsed": 0.1}"""),
        new("controls_and_ints",
            Body: """{"playing": true, "title": "a\u0001b\u007fc\u2028d\u001f", "artist": "~ tilde", "album": "X", "duration": 245, "elapsed": 12, "store_id": "1440894925"}""",
            Age: 30.0,
            Artwork: new() {  },
            Links: new() { ["1440894925"] = new CatalogLinks(null, "https://music.apple.com/us/artist/k/3", "https://music.apple.com/us/album/i/1") },
            Expected: """{"playing": true, "stale": false, "updated_ago": 30.0, "title": "a\u0001b\u007fc\u2028d\u001f", "artist": "~ tilde", "album": "X", "duration": 245.0, "elapsed": 12.0, "links": {"artist": "https://music.apple.com/us/artist/k/3", "album": "https://music.apple.com/us/album/i/1"}}"""),
        new("clock_skew",
            Body: """{"playing": true, "title": "Ahead", "artist": "A", "duration": 100.05}""",
            Age: -5.0,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": true, "stale": false, "updated_ago": -5.0, "title": "Ahead", "artist": "A", "duration": 100.0}"""),
        new("truthy_playing",
            Body: """{"playing": 1, "title": "One", "artist": "A", "seq": 7}""",
            Age: 2.0,
            Artwork: new() {  },
            Links: new() {  },
            Expected: """{"playing": true, "stale": false, "updated_ago": 2.0, "title": "One", "artist": "A"}""")
    ];

    public static TheoryData<string> CaseNames => new(Cases.Select(c => c.Name));

    /// <summary>Puts the phone, the artwork cache and the clock into the state <paramref name="parity"/> describes.</summary>
    internal static void Arrange(Case parity, FakePhoneState phone, FakeArtwork artwork, ManualClock clock)
    {
        clock.Now = Now;
        if (parity.Body is null)
            phone.Set(null, 0);
        else
            phone.Set(NowPlayingPush.Parse(JsonNode.Parse(parity.Body)!.AsObject()).Track, Now - parity.Age!.Value);

        foreach (var (storeId, url) in parity.Artwork)
            artwork.Covers[storeId] = url;
        foreach (var (storeId, links) in parity.Links)
            artwork.Links[storeId] = links;
    }

    [Theory]
    [MemberData(nameof(CaseNames))]
    public void Matches_relay_py_public_state(string name)
    {
        var parity = Cases.Single(c => c.Name == name);
        var phone = new FakePhoneState();
        var artwork = new FakeArtwork();
        var clock = new ManualClock();
        Arrange(parity, phone, artwork, clock);

        Assert.Equal(parity.Expected, NowPlayingProjection.Json(phone, artwork, clock.Now));
        Assert.Equal(0, artwork.ResolveCalls);
    }

    /// <summary>
    /// The machine's culture is not Issun's to choose. sv-SE writes decimals
    /// with a comma and negatives with U+2212, so any number that reached the
    /// wire through the current culture would show up here. The culture is set
    /// on this test's thread only, so tests running in parallel are unaffected.
    /// </summary>
    [Theory]
    [MemberData(nameof(CaseNames))]
    public void Matches_relay_py_whatever_the_machines_culture(string name)
    {
        var previous = System.Globalization.CultureInfo.CurrentCulture;
        System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("sv-SE");
        try
        {
            var parity = Cases.Single(c => c.Name == name);
            var phone = new FakePhoneState();
            var artwork = new FakeArtwork();
            var clock = new ManualClock();
            Arrange(parity, phone, artwork, clock);

            Assert.Equal(parity.Expected, NowPlayingProjection.Json(phone, artwork, clock.Now));
        }
        finally
        {
            System.Globalization.CultureInfo.CurrentCulture = previous;
        }
    }

    [Fact]
    public void The_projection_leaves_out_the_upload_and_the_diag_block()
    {
        var parity = Cases.Single(c => c.Name == "full");
        Assert.Contains("artwork_b64", parity.Body);
        Assert.DoesNotContain("artwork_b64", parity.Expected);
        Assert.DoesNotContain("diag", parity.Expected);
        Assert.DoesNotContain("seq", parity.Expected);
    }

    [Fact]
    public void A_store_id_with_whitespace_still_finds_its_cached_cover()
    {
        // relay.py looked the cache up with the untrimmed ID while build_payload
        // had stored it under the trimmed one, so " 42 " never found its cover.
        // TrackInfo.StoreId is trimmed at parse time; the lookup here uses it.
        var phone = new FakePhoneState();
        var artwork = new FakeArtwork();
        artwork.Covers["42"] = "https://example.invalid/42.jpg";
        phone.Set(NowPlayingPush.Parse(JsonNode.Parse("""{"playing": true, "title": "T", "store_id": " 42 "}""")!.AsObject()).Track, Now - 1);

        Assert.Equal(
            """{"playing": true, "stale": false, "updated_ago": 1.0, "title": "T", "artwork": "https://example.invalid/42.jpg"}""",
            NowPlayingProjection.Json(phone, artwork, Now));
    }

    [Fact]
    public void Non_finite_numbers_are_left_out_rather_than_written_as_bare_tokens()
    {
        var phone = new FakePhoneState();
        phone.Set(new TrackInfo { Title = "T", Duration = double.PositiveInfinity, Elapsed = double.NaN }, Now - 1);

        Assert.Equal(
            """{"playing": true, "stale": false, "updated_ago": 1.0, "title": "T"}""",
            NowPlayingProjection.Json(phone, new FakeArtwork(), Now));
    }

    // ─────────────────────── Python's round() and repr() ───────────────────────

    /// <summary>
    /// (repr(x), json.dumps(round(x, 1))) pairs from Python 3.14. The ties and
    /// near-ties are the point: 0.35, 2.675 and 231.45 sit just below their
    /// midpoints in binary, 0.25 and -2.5 are exact ties that go to even.
    /// </summary>
    [Theory]
    [InlineData("0.05", "0.1")]
    [InlineData("0.15", "0.1")]
    [InlineData("0.25", "0.2")]
    [InlineData("0.35", "0.3")]
    [InlineData("0.45", "0.5")]
    [InlineData("0.55", "0.6")]
    [InlineData("2.675", "2.7")]
    [InlineData("12.35", "12.3")]
    [InlineData("231.45", "231.4")]
    [InlineData("-0.04", "-0.0")]
    [InlineData("-0.05", "-0.1")]
    [InlineData("-0.15", "-0.1")]
    [InlineData("-2.5", "-2.5")]
    [InlineData("1e+16", "1e+16")]
    [InlineData("1000000000000000.0", "1000000000000000.0")]
    [InlineData("1e-05", "0.0")]
    [InlineData("0.0001", "0.0")]
    [InlineData("123456.789", "123456.8")]
    [InlineData("99.95", "100.0")]
    [InlineData("89.95", "90.0")]
    [InlineData("3.25", "3.2")]
    [InlineData("7.75", "7.8")]
    [InlineData("0.0", "0.0")]
    [InlineData("1.05", "1.1")]
    [InlineData("4.35", "4.3")]
    [InlineData("1e+22", "1e+22")]
    [InlineData("5e-324", "0.0")]
    [InlineData("1.7976931348623157e+308", "1.7976931348623157e+308")]
    [InlineData("4503599627370495.5", "4503599627370495.5")]
    [InlineData("450359962737049.56", "450359962737049.6")]
    [InlineData("45035996273704.95", "45035996273705.0")]
    [InlineData("-352.33", "-352.3")]
    [InlineData("-210.4", "-210.4")]
    [InlineData("-855.1", "-855.1")]
    [InlineData("-268.6", "-268.6")]
    [InlineData("819.41", "819.4")]
    [InlineData("-925.0087", "-925.0")]
    [InlineData("-163.66", "-163.7")]
    [InlineData("-818.574", "-818.6")]
    [InlineData("-881.8", "-881.8")]
    [InlineData("894.9", "894.9")]
    [InlineData("154.2059", "154.2")]
    [InlineData("-900.82", "-900.8")]
    [InlineData("-906.83", "-906.8")]
    [InlineData("-420.78", "-420.8")]
    [InlineData("81.372", "81.4")]
    [InlineData("120.51", "120.5")]
    [InlineData("-793.89", "-793.9")]
    [InlineData("-255.2", "-255.2")]
    [InlineData("128.74", "128.7")]
    [InlineData("-7.171", "-7.2")]
    [InlineData("554.4575", "554.5")]
    [InlineData("171.1237", "171.1")]
    [InlineData("-276.84", "-276.8")]
    [InlineData("588.76", "588.8")]
    [InlineData("-836.29", "-836.3")]
    [InlineData("50.393", "50.4")]
    [InlineData("458.891", "458.9")]
    [InlineData("217.9", "217.9")]
    [InlineData("-763.8684", "-763.9")]
    [InlineData("-670.076", "-670.1")]
    [InlineData("-696.0309", "-696.0")]
    [InlineData("-156.6", "-156.6")]
    [InlineData("529.142", "529.1")]
    [InlineData("-319.755", "-319.8")]
    [InlineData("188.7398", "188.7")]
    [InlineData("-862.5", "-862.5")]
    [InlineData("889.3622", "889.4")]
    [InlineData("394.1", "394.1")]
    [InlineData("-878.661", "-878.7")]
    [InlineData("294.2577", "294.3")]
    public void Round_and_repr_match_python(string repr, string rounded)
    {
        var x = double.Parse(repr, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture);
        Assert.Equal(repr, PyJson.FloatRepr(x));
        Assert.Equal(rounded, PyJson.FloatRepr(PyJson.Round(x, 1)));
    }
}
